version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ofcolor
    ports:
      - '5450:5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql


